# Generated by Django 3.1.2 on 2020-10-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colour',
            field=models.ManyToManyField(to='backend.Colors'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ManyToManyField(to='backend.Size'),
        ),
    ]
