import { actionTypes } from "redux-form";
import ProductDetail from "../components/home/ProductDetail";

// user related actions
export const USER_LOADING = 'USER_LOADING'; // added
export const USER_LOADED = 'USER_LOADED'; // added
export const AUTH_ERROR = 'AUTH_ERROR'; // added
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; // added
export const REGISTER_FAIL = 'REGISTER_FAIL'; // added
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; // added
export const LOGIN_FAIL = 'LOGIN_FAIL'; // added
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; // added
export const ADDED_SUCCESSFULLY = 'ADDED_SUCCESSFULLY'; // added
export const ACTION_START = 'ACTION_START';

// products related actions
export const GET_SHIRT_PRODUCTS = 'GET_SHIRT_PRODUCTS';
export const GET_TSHIRT_PRODUCTS = 'GET_TSHIRT_PRODUCTS';
export const GET_PANT_PRODUCTS = 'GET_PANT_PRODUCTS';

// cart related actions
export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CART = 'FETCH_CART';
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAILED = 'CART_ADD_FAILED';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const REMOVE_CART_FAILED = 'REMOVE_CART_FAILED';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const REMOVED_QUANTITY_SUCCESS = 'REMOVED_QUANTITY_SUCCESS';
export const QUANTITY_ACTION_FAILED = 'QUANTITY_ACTION_FAILED';
export const ADD_QUANTITY_SUCCESS = 'ADD_QUANTITY_SUCCESS';

/* ProductDetail actionTypes */
export const FETCH_PRODUCT_DETAIL_SUCCESS = 'FETCH_PRODUCT_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL_FAILED = 'FETCH_PRODUCT_DETAIL_FAILED';



// profile related actions
export const ADDRESS_SAVING = 'ADDRESS_SAVING';
export const ADDRESS_SAVED_SUCCESSFULLY = 'ADDRESS_SAVED_SUCCESSFULLY';
export const ADDESS_SAVING_FAIED = 'ADDESS_SAVING_FAIED';
export const ADDRESS_UPDATING = 'ADDRESS_UPDATING';
export const ADDRESS_UPDATE_SUCCESSFULLY = 'ADDRESS_UPDATE_SUCCESSFULLY';
export const ADDRESS_UPDATE_FAILED = 'ADDRESS_UPDATE_FAILED';
export const ADDRESS_FETCHING = 'ADDRESS_FETCHING';
export const ADDRESS_FETCHED_SUCCESSFULLY = 'ADDRESS_FETCHED_SUCCESSFULLY';
export const ADDRESS_FETCHING_FAIED = 'ADDRESS_FETCHING_FAIED';
export const ADDRESS_DELETING = 'ADDRESS_DELETING';
export const ADDRESS_DELETING_SUCCESSFULLY = 'ADDRESS_DELETING_SUCCESSFULLY';
export const ADDRESS_DELETING_FAIED = 'ADDRESS_DELETING_FAIED';


// cart related actions
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const REMOVE_ORDER = 'REMOVE_FROM_CART';
export const ORDER_UPDATE_SUSSESS = 'ORDER_UPDATE_SUSSESS';
export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS';

/* Coupon Related actionTypes */
export const ADDING_COUPON = 'ADDING_COUPON';
export const ADDED_COUPON_SUSSESFULLY = 'ADDED_COUPON_SUSSESFULLY';
export const ADDING_COUPON_FAILED = 'ADDING_COUPON_FAILED';
export const FETCHING_COUPON = 'FETCHING_COUPON';
export const FETCHING_COUPON_SUCCESS = 'FETCHING_COUPON_SUCCESS';
export const FETCHING_COUPON_FAILED = 'FETCHING_COUPON_FAILED';






